In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix


In [5]:
# Load dataset
data = pd.read_csv('/content/BankNote_Authentication.csv')

# Display dataset info
print("Dataset Preview:\n", data.head(10))




Dataset Preview:
    variance  skewness  curtosis  entropy  class
0   3.62160    8.6661  -2.80730 -0.44699      0
1   4.54590    8.1674  -2.45860 -1.46210      0
2   3.86600   -2.6383   1.92420  0.10645      0
3   3.45660    9.5228  -4.01120 -3.59440      0
4   0.32924   -4.4552   4.57180 -0.98880      0
5   4.36840    9.6718  -3.96060 -3.16250      0
6   3.59120    3.0129   0.72888  0.56421      0
7   2.09220   -6.8100   8.46360 -0.60216      0
8   3.20320    5.7588  -0.75345 -0.61251      0
9   1.53560    9.1772  -2.27180 -0.73535      0


In [3]:
print("\nDataset Dimensions:", data.shape)


Dataset Dimensions: (1372, 5)


In [4]:
print("\nDescriptive Statistics:\n", data.describe())


Descriptive Statistics:
           variance     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000


In [6]:
# Split dataset into features and target
X = data.drop(columns='class')
y = data['class']


In [7]:
def train_and_evaluate(test_size):
    print(f"\nTraining with test_size={test_size}...\n")

    # Split dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)

    for activation in ['relu', 'logistic', 'tanh', 'identity']:
        print(f"\nMLPClassifier with activation='{activation}':")

        # Train model
        mlp = MLPClassifier(max_iter=500, activation=activation, random_state=42)
        mlp.fit(X_train, y_train)

        # Make predictions
        y_pred = mlp.predict(X_test)

        # Display results
        print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
        print("\nClassification Report:\n", classification_report(y_test, y_pred))


In [9]:
# Run training with different train-test splits
train_and_evaluate(test_size=0.2)



Training with test_size=0.2...


MLPClassifier with activation='relu':
Confusion Matrix:
 [[148   0]
 [  0 127]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


MLPClassifier with activation='logistic':
Confusion Matrix:
 [[148   0]
 [  1 126]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       148
           1       1.00      0.99      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


MLPClassifier with activation='tanh':
Confusion Matrix:
 [[148   0]
 [  0 127]]

Classification 

In [10]:
train_and_evaluate(test_size=0.3)



Training with test_size=0.3...


MLPClassifier with activation='relu':
Confusion Matrix:
 [[229   0]
 [  0 183]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      1.00      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412


MLPClassifier with activation='logistic':
Confusion Matrix:
 [[229   0]
 [  1 182]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      0.99      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412


MLPClassifier with activation='tanh':
Confusion Matrix:
 [[229   0]
 [  0 183]]

Classification 